"use server";

import { z } from "zod";
import { runAction } from "@/lib/api/response";
import { requireActor } from "@/lib/auth/dal";
import { AppError, fromDatabaseError } from "@/lib/errors";
import { createSessionClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

// Buyer actions (favorite.add/remove, enquiry.create, history.clear). All run
// with the user's session: RLS and create_enquiry() enforce ownership,
// visibility, duplicates and rate limits.

const uuid = z.uuid();

export async function setFavoriteAction(propertyId: string, saved: boolean) {
  return runAction("favorite.set", async () => {
    if (!uuid.safeParse(propertyId).success) throw new AppError("PROPERTY_NOT_FOUND");
    const actor = await requireActor();
    const supabase = await createSessionClient();
    if (saved) {
      const { error } = await supabase.from("favorites").insert({ property_id: propertyId });
      // Already saved is success (double click, second tab).
      if (error && error.code !== "23505") {
        if (error.code === "42501") throw new AppError("PROPERTY_NOT_AVAILABLE");
        throw fromDatabaseError(error);
      }
    } else {
      const { error } = await supabase.from("favorites").delete().eq("user_id", actor.id).eq("property_id", propertyId);
      if (error) throw fromDatabaseError(error);
    }
    revalidatePath("/dashboard/saved");
    return { propertyId, saved };
  });
}

const enquirySchema = z.strictObject({
  propertyId: z.uuid(),
  message: z.string().max(1000).optional(),
  // Generated by the form when it opens; a retried submit reuses it (ENQ, CONC-002).
  idempotencyKey: z.uuid(),
});

export async function createEnquiryAction(input: unknown) {
  return runAction("enquiry.create", async () => {
    const parsed = enquirySchema.safeParse(input);
    if (!parsed.success) throw new AppError("VALIDATION_FAILED", { detail: "message" });
    await requireActor();
    const supabase = await createSessionClient();
    const { data, error } = await supabase.rpc("create_enquiry", {
      p_property_id: parsed.data.propertyId,
      p_message: parsed.data.message?.trim() || null,
      p_idempotency_key: parsed.data.idempotencyKey,
    });
    if (error) throw fromDatabaseError(error);
    revalidatePath("/dashboard/enquiries");
    return data as { enquiry_id: string; replayed: boolean };
  });
}

export async function clearRecentlyViewedAction() {
  return runAction("history.clear", async () => {
    const actor = await requireActor();
    const supabase = await createSessionClient();
    const { error } = await supabase.from("recently_viewed").delete().eq("user_id", actor.id);
    if (error) throw fromDatabaseError(error);
    revalidatePath("/dashboard/recent");
    return { cleared: true };
  });
}

/** Recently viewed (HISTORY). Records only visible listings for the caller;
 *  silently ignores guests and hidden listings. */
export async function recordViewAction(propertyId: string) {
  if (!uuid.safeParse(propertyId).success) return;
  try {
    await requireActor();
    const supabase = await createSessionClient();
    await supabase.rpc("record_property_view", { p_property_id: propertyId });
  } catch {
    // Best effort: history must never break the page.
  }
}
